### PR TITLE
Properly package TWED as installable Python package

### PR DESCRIPTION
**Pull request by marcus-voss**
I addressed some steps (adding Setup.py + some changes in the wrapper file), so that your wrapper is now installable via `pip install .`

Some points to discuss:
- Should the "src" folder be called twed or pytwed? If it were Python code and a proper module, I'd say yes, but C/C++ code I see more often in a src folder. 
- Should the "name" in setup.py be twed or pytwed?
- I guess license needs to be a GPL, as the original code was GPL?
- Is authors okay like that, i.e., is there still most code from Marteau?
- Should the paper from Marteau be added to the readme?

Ideas for further improvements would be:
- adding a minimal test file to check the install (pytest or just unittest package),
- expose mu, lambda and degree as parameters to the python code

### CODE REVIEW

**Review by jzumer — CHANGES_REQUESTED** [review]
Please add a `requirements.txt` since `numpy` and `cython` for this package.
It may also be good to generate wheels (via `python3 setup.py sdist bdist_wheel`).

**Review by jzumer — CHANGES_REQUESTED** [review]
Usagage -> Usage
build_example.sh probably should be kept so that users who can't use/don't want to use cython can manually build the library anyway

**Comment by jzumer** [comment]
>Should the "src" folder be called twed or pytwed? If it were Python code and a proper module, I'd say yes, but C/C++ code I see more often in a src folder.

`twed.c` and `twed_wrap.c` were just a C wrapper and the lightly modified original source, this was for all intents and purposes not really a python package at the time. I think `pytwed` is more appropriate now.
>Should the "name" in setup.py be twed or pytwed?
It seems the "usual" is to call the repository "pytwed" but to call the module "twed".

>I guess license needs to be a GPL, as the original code was GPL?

The original code only specifies "GPL" and only in passing. It also does not actually satisfy the GPL license requirements so it doesn't actually technically is GPL-licensed (it merely "claims" to be GPL). No version of GPL is specified either.
Nevertheless, this should probably be GPLv3 for simplicity's sake. Legally speaking, I am not an expert in this subject, though. What do you think?

>Is authors okay like that, i.e., is there still most code from Marteau?

Only the file `twed.c` was originally from Marteau, the rest was originally from me. Author attribution looks good to me.

>Should the paper from Marteau be added to the readme?

I think it's a good idea. The reference is in bibtex format in the `twed.c` file.
A link to it from the title "Time Warp Edit Distance with Stiffness Adjustment for Time Series Matching" (URL: http://dx.doi.org/10.1109/TPAMI.2008.76) should do.

**Comment by jzumer** [comment]
I have tested it on a Linux box and it works as expected, so that's good news as well.

Thank you for the contribution, I will merge the PR as soon as the few details above are settled.

**Comment by marcus-voss** [comment]
> Please add a `requirements.txt` since `numpy` and `cython` for this package.
> It may also be good to generate wheels (via `python3 setup.py sdist bdist_wheel`).

`requirements.txt` is added. Cython is not needed now only numpy. As it is already in the header of the setup.py it can't be installed automatically. Is added to readme in install section.

**Comment by marcus-voss** [comment]
> Usagage -> Usage
> build_example.sh probably should be kept so that users who can't use/don't want to use cython can manually build the library anyway

Fixed the typos and actually added quite a bit of more documentation. Hope that is fine with you. Took out some claims like the "it is the best metric" or something, but made the motivation more explicit in comparison to DTW. 

Readded the build script and added it as second option to the documentation.

**Comment by marcus-voss** [comment]
> twed.c and twed_wrap.c were just a C wrapper and the lightly modified original source, this was for all intents and purposes not really a python package at the time. I think pytwed is more appropriate now.

I now named the package pywed. One can now still work with the import twed, but I think now the import pytwed is more appropriate.

**Comment by marcus-voss** [comment]
> I guess license needs to be a GPL, as the original code was GPL?
> 
> The original code only specifies "GPL" and only in passing. It also does not actually satisfy the GPL license requirements so it doesn't actually technically is GPL-licensed (it merely "claims" to be GPL). No version of GPL is specified either.
> Nevertheless, this should probably be GPLv3 for simplicity's sake. Legally speaking, I am not an expert in this subject, though. What do you think?

Also not an expert on this. I usually try to use MIT to avoid all this downstream stuff. But I guess with GPLv3 we should be fine, and I added a proper license from the Github templates.

**Comment by marcus-voss** [comment]
> It may also be good to generate wheels (via python3 setup.py sdist bdist_wheel).

Not sure about this step. So which files would one check into the repo then? And this should be done on a linx, best, right?

**Comment by marcus-voss** [comment]
One last point to discuss. I had to change parameter `lambda` to `lmbda` to not use the reserved Python keyword. I renamed `mu` to `gamma` to be consistent with the paper. I saw he used `nu` in his code, which is not really a greek letter. So I'd prefer to be consistent with the paper here. What do you think? I also added the parameters to the example and added basic explanation to be more useful to people (at least that is what I'd expect to find).

**Comment by marcus-voss** [comment]
> One last point to discuss. I had to change parameter `lambda` to `lmbda` to not use the reserved Python keyword. I renamed `mu` to `gamma` to be consistent with the paper. I saw he used `nu` in his code, which is not really a greek letter. So I'd prefer to be consistent with the paper here. What do you think? I also added the parameters to the example and added basic explanation to be more useful to people (at least that is what I'd expect to find).

Ah, okay. Now found the confusion. So in your wrapper you referred to it as mu, in the preprint it was called gamma. However, in the published paper it is nu (which is a greek letter, my bad). So made it consistent with the published paper (which is as in his original code).

**Review by jzumer — CHANGES_REQUESTED** [review]
is probably distance metric -> is a distance metric

**Review by jzumer — CHANGES_REQUESTED** [review]
The link to use should really be the doi, it links to the actual publication instead of the preprint, and it is clearer for references.

**Review by jzumer — COMMENTED** [review]
"We are providing..." is usually phrased "this code is provided..." (of course, this is merely a stylistic issue).

**Comment by jzumer** [comment]
I wanted to add you as a collaborator since you're clearly more invested than me now, but the github website is quite broken in my browser. I'll try to fix this somehow. If not, once your changes are merged, I can add a comment in the header of the readme in my repo pointing to your repo's version as being the reference version if you like.

**Comment by jzumer** [comment]
For generating wheels: they are generated based on the current architecture, so you would like to generate one on linux, one on mac, one on windows...
Alternatively, pointing out the instructions for building the wheel (the command above) is OK, too, since we don't have access to every machine ourselves.

**Comment by marcus-voss** [comment]
> The link to use should really be the doi, it links to the actual publication instead of the preprint, and it is clearer for references.

Yeah, you're right. Especially now that there are some differences between published and preprint version. Done.

> "We are providing..." is usually phrased "this code is provided..." (of course, this is merely a stylistic issue).

Done. 

> is probably distance metric -> is a distance metric

I can't find this part. Or do you mean adding the "probably"? Have your read somewhere doubts about the TWED being metric? If there is a counterargument, okay, we can add the probably (+ reference), but unless that is not the case, I think we are fine claiming it here until proven otherwise. 

> For generating wheels: they are generated based on the current architecture, so you would like to generate one on linux, one on mac, one on windows...
> Alternatively, pointing out the instructions for building the wheel (the command above) is OK, too, since we don't have access to every machine ourselves.

But what is the advantage of it? For the users not having to install C compiler, I suppose?

**Review by jzumer — APPROVED** [review]

**Comment by jzumer** [comment]
>I can't find this part. 
It was addressed in a later commit that I hadn't seen yet, there was part of the previous sentence (ending in 'probably') still in there, and a missing 'a' before 'metric', hence the phrase 'is probably distance metric' (originally, 'is probably the best distance metric' or such) should have been corrected to 'is a distance metric'. This is not actually a problem with the future commits added. My bad.

>For the users not having to install C compiler, I suppose?
It lets users just install the package outright with all the preprocessing already completed. Beyond not needing a C compiler, it also doesn't depend on the downstream version of the C compiler.
In this case it's really just convenience since the compilation is not long (as it is in some other packages) and the install steps are simple.

With the changes applied, I will now be closing this PR. The next steps are one of the following:
- Port the changes back to Marteau's repository, or
- Keep this as an alternative repository to Marteau's version, in which case let me know if you want to be considered the current maintainer (I will simply be redirecting people to your repo from the readme in mine).

**Pull request merged**
